[package]
name = "cto-bonding"
version = "0.1.0"
description = "CTO Agent Bonding Curve Program"
edition = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]
name = "cto_bonding"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
spl-token = "4.0"
